### ISSUE TITLE
A question about your patches

### ISSUE THREAD

**Issue by Ahmed-E-86** [leonmaxx/wine-dxvk-rpm#1]
I don't use Fedora, I use Manjaro, and TKG builds is the ideal choice for me, so I want to build TKG with your patches, so I need to know what are these patches do:
**1- wine-amd_ags.patch.
2- wine-cjk.patch.**
Thanks in advance.

**Comment by leonmaxx** [comment]
1. It's from Wine-Proton it adds amd_ags_x64.dll with couple of Vulkan functions. On Windows this dll is installed by AMD drivers.
2. Fedora's patch for wine to register some asian fonts.

**Comment by Ahmed-E-86** [comment]
Thanks. One more question. Is it wine-staging or plain-wine?

**Comment by leonmaxx** [comment]
It' plain wine but with 3 patches from wine-staging:
1. winepulse-PulseAudio_Support
2. ntdll-User_Shared_Data
3. fonts-Missing_Fonts

**Comment by Ahmed-E-86** [comment]
Thanks.
